[package]
name = "onchainVampireSurvivors-v1.0.0"
version = "1.0.0"
authors = []

[addresses]
hello_blockchain = "0x5da29a405371ee7c13caef1b53008c39a8b7692b5d0eed5ed36707360ed9cddc"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
